SOCKSMETHOD="none"
[ "$AUTH_ENABLED" = "true" ] && SOCKSMETHOD="username"

PROTOCOL="tcp"
[ "${UDP_ENABLED:-false}" = "true" ] && PROTOCOL="tcp udp"

_log_rule='connect disconnect error'
[ "${LOG_LEVEL:-normal}" = "quiet" ] && _log_rule='error'

{
    printf '# Auto-generated by entrypoint.sh — do not edit manually\n'
    if [ "${LOG_LEVEL:-normal}" = "quiet" ]; then
        printf 'logoutput: /dev/null\n\n'
    else
        printf 'logoutput: stderr\n\n'
    fi

    printf 'internal: 0.0.0.0 port = 1080\n'
    [ "${IPV6_ENABLED:-false}" = "true" ] && printf 'internal: :: port = 1080\n'

    # Performance optimization: Increase listen backlog
    printf 'internal.backlog: 1024\n'

    printf 'external: %s\n\n' "$IFACE"
    printf 'clientmethod: none\n'
    printf 'socksmethod: %s\n\n' "$SOCKSMETHOD"
    printf 'user.privileged: root\n'
    printf 'user.notprivileged: nobody\n\n'
    printf 'timeout.connect: %s\n'   "${TIMEOUT_CONNECT:-30}"
    printf 'timeout.negotiate: %s\n' "${TIMEOUT_NEGOTIATE:-30}"
    printf 'timeout.io: %s\n\n'      "${TIMEOUT_IO:-86400}"

    if [ -n "${ALLOWED_CIDR:-}" ]; then
        log "INFO: Applying IP allowlist: $ALLOWED_CIDR"
        # Use IFS=', ' to handle both commas and spaces without forking tr
        _save="$IFS"; IFS=', '
        for _cidr in $ALLOWED_CIDR; do
            [ -z "$_cidr" ] && continue
            printf 'client pass {\n    from: %s to: 0.0.0.0/0\n    log: %s\n}\n\n' "$_cidr" "$_log_rule"
        done
        IFS="$_save"
        printf 'client block {\n    from: 0.0.0.0/0 to: 0.0.0.0/0\n    log: error\n}\n\n'
    else
        printf 'client pass {\n    from: 0.0.0.0/0 to: 0.0.0.0/0\n    log: %s\n}\n\n' "$_log_rule"
    fi

    if [ -n "${BLOCKED_DESTINATIONS:-}" ]; then
        log "INFO: Blocking destinations: $BLOCKED_DESTINATIONS"
        # Use IFS=', ' to handle both commas and spaces without forking tr
        _save="$IFS"; IFS=', '
        for _dest in $BLOCKED_DESTINATIONS; do
            [ -z "$_dest" ] && continue
            printf 'socks block {\n    from: 0.0.0.0/0 to: %s\n    log: error\n}\n\n' "$_dest"
        done
        IFS="$_save"
    fi

    printf 'socks pass {\n'
    printf '    from: 0.0.0.0/0 to: 0.0.0.0/0\n'
    printf '    protocol: %s\n' "$PROTOCOL"
    printf '    log: %s\n' "$_log_rule"
    printf '}\n'

    if [ "${TOR_ENABLED:-false}" = "true" ]; then
        printf '\nroute {\n'
        printf '    from: 0.0.0.0/0 to: 0.0.0.0/0 via: 127.0.0.1 port = 9050\n'
        printf '    protocol: tcp\n'
        printf '    method: none\n'
        printf '    proxyprotocol: socks_v5\n'
        printf '}\n'
    fi
} > "$CONF"

log "INFO: Dante configuration written to $CONF"
