SOCKSMETHOD="none"
[ "$AUTH_ENABLED" = "true" ] && SOCKSMETHOD="username"

PROTOCOL="tcp"
[ "${UDP_ENABLED:-false}" = "true" ] && PROTOCOL="tcp udp"

_log_rule='connect disconnect error'
[ "${LOG_LEVEL:-normal}" = "quiet" ] && _log_rule='error'

_resolve_all() {
    getent hosts "$1" 2>/dev/null | while read -r ip _; do
        [ -n "$ip" ] && printf '%s/32\n' "$ip"
    done | sort -u
}

_normalize_ip() {
    case "$1" in
        */*) printf '%s' "$1" ;;
        *)   printf '%s/32' "$1" ;;
    esac
}

{
    printf '# Auto-generated by entrypoint.sh -- do not edit manually\n'
    if [ "${LOG_LEVEL:-normal}" = "quiet" ]; then
        printf 'logoutput: /dev/null\n\n'
    else
        printf 'logoutput: stderr\n\n'
    fi

    printf 'internal: 0.0.0.0 port = 1080\n'
    [ "${IPV6_ENABLED:-false}" = "true" ] && printf 'internal: :: port = 1080\n'

    printf 'external: %s\n\n' "$IFACE"
    printf 'clientmethod: none\n'
    printf 'socksmethod: %s\n\n' "$SOCKSMETHOD"
    printf 'user.privileged: root\n'
    printf 'user.notprivileged: nobody\n\n'
    printf 'timeout.connect: %s\n'   "${TIMEOUT_CONNECT:-30}"
    printf 'timeout.negotiate: %s\n' "${TIMEOUT_NEGOTIATE:-30}"
    printf 'timeout.io: %s\n\n'      "${TIMEOUT_IO:-86400}"

    # --- Client-level rules (source IP filtering) ---

    if [ -n "${ALLOWED_CIDR:-}" ]; then
        log "INFO: Applying IP allowlist: $ALLOWED_CIDR"
        _save="$IFS"; IFS=','
        for _cidr in $ALLOWED_CIDR; do
            IFS="$_save"
            _cidr=$(printf '%s' "$_cidr" | tr -d ' ')
            printf 'client pass {\n    from: %s to: 0.0.0.0/0\n    log: %s\n}\n\n' "$_cidr" "$_log_rule"
            IFS=','
        done
        IFS="$_save"
        printf 'client block {\n    from: 0.0.0.0/0 to: 0.0.0.0/0\n    log: error\n}\n\n'
    else
        printf 'client pass {\n    from: 0.0.0.0/0 to: 0.0.0.0/0\n    log: %s\n}\n\n' "$_log_rule"
    fi

    # --- IP-based destination blocks ---

    if [ -n "${BLOCKED_DESTINATIONS:-}" ]; then
        log "INFO: Blocking IP destinations: $BLOCKED_DESTINATIONS"
        _save="$IFS"; IFS=','
        for _dest in $BLOCKED_DESTINATIONS; do
            IFS="$_save"
            _dest=$(printf '%s' "$_dest" | tr -d ' ')
            _dest=$(_normalize_ip "$_dest")
            printf 'socks block {\n    from: 0.0.0.0/0 to: %s\n    log: error\n}\n\n' "$_dest"
            IFS=','
        done
        IFS="$_save"
    fi

    # --- Domain-based destination blocks ---

    if [ -n "${BLOCKED_DOMAINS:-}" ]; then
        log "INFO: Blocking destination domains: $BLOCKED_DOMAINS"
        _save="$IFS"; IFS=','
        for _domain in $BLOCKED_DOMAINS; do
            IFS="$_save"
            _domain=$(printf '%s' "$_domain" | tr -d ' ')
            _ips=$(_resolve_all "$_domain")
            if [ -n "$_ips" ]; then
                for _ip in $_ips; do
                    printf 'socks block {\n    from: 0.0.0.0/0 to: %s\n    log: error\n}\n\n' "$_ip"
                done
            else
                log "WARN: Could not resolve domain: $_domain (skipping)"
            fi
            IFS=','
        done
        IFS="$_save"
    fi

    # --- Domain-based destination allowlist ---

    if [ -n "${ALLOWED_DOMAINS:-}" ]; then
        log "INFO: Applying domain allowlist: $ALLOWED_DOMAINS"
        _save="$IFS"; IFS=','
        for _domain in $ALLOWED_DOMAINS; do
            IFS="$_save"
            _domain=$(printf '%s' "$_domain" | tr -d ' ')
            _ips=$(_resolve_all "$_domain")
            if [ -n "$_ips" ]; then
                for _ip in $_ips; do
                    printf 'socks pass {\n    from: 0.0.0.0/0 to: %s\n    protocol: %s\n    log: %s\n}\n\n' "$_ip" "$PROTOCOL" "$_log_rule"
                done
            else
                log "WARN: Could not resolve domain: $_domain (skipping)"
            fi
            IFS=','
        done
        IFS="$_save"
        # Catch-all block - only allowed domains pass
        printf 'socks block {\n    from: 0.0.0.0/0 to: 0.0.0.0/0\n    log: error\n}\n\n'
    fi

    # Default catch-all socks pass (when no domain allowlist restricts everything)
    if [ -z "${ALLOWED_DOMAINS:-}" ]; then
        printf 'socks pass {\n'
        printf '    from: 0.0.0.0/0 to: 0.0.0.0/0\n'
        printf '    protocol: %s\n' "$PROTOCOL"
        printf '    log: %s\n' "$_log_rule"
        printf '}\n'
    fi

    # --- Route rules ---

    if [ "${TOR_ENABLED:-false}" = "true" ]; then
        printf '\nroute {\n'
        printf '    from: 0.0.0.0/0 to: 0.0.0.0/0 via: 127.0.0.1 port = 9050\n'
        printf '    protocol: tcp\n'
        printf '    method: none\n'
        printf '    proxyprotocol: socks_v5\n'
        printf '}\n'
    fi

    if [ -n "${UPSTREAM_PROXY:-}" ]; then
        log "INFO: Configuring upstream proxy(ies): $UPSTREAM_PROXY"
        _save="$IFS"; IFS=','
        for _proxy in $UPSTREAM_PROXY; do
            IFS="$_save"
            _proxy=$(printf '%s' "$_proxy" | tr -d ' ')
            _rest="${_proxy#*://}"
            case "$_rest" in
                *@*)
                    _userpass="${_rest%%@*}"
                    _hostport="${_rest#*@}"
                    _usr="${_userpass%%:*}"
                    _pwd="${_userpass#*:}"
                    _auth="username"
                    ;;
                *)
                    _usr=""; _pwd=""; _auth="none"
                    _hostport="$_rest"
                    ;;
            esac
            _host="${_hostport%%:*}"
            _port="${_hostport#*:}"
            [ "$_host" = "$_port" ] && _port="1080"
            printf '\nroute {\n'
            printf '    from: 0.0.0.0/0 to: 0.0.0.0/0 via: %s port = %s\n' "$_host" "$_port"
            printf '    command: connect\n'
            printf '    protocol: tcp\n'
            printf '    method: %s\n' "$_auth"
            if [ "$_auth" = "username" ] && [ -n "$_usr" ]; then
                printf '    username: "%s"\n' "$_usr"
                printf '    password: "%s"\n' "$_pwd"
            fi
            printf '    proxyprotocol: socks_v5\n'
            printf '}\n'
            log "INFO:   -> route via $_host:$_port (auth: $_auth)"
            IFS=','
        done
        IFS="$_save"
    fi
} > "$CONF"

log "INFO: Dante configuration written to $CONF"
