#!/bin/sh
set -e

CONF=/etc/danted.conf

log() { printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >&2; }

# ── 0. Kernel TCP performance tuning (best-effort; requires host sysctls or privileged) ──
_sysctl() { sysctl -w "$1" >/dev/null 2>&1 || true; }
_sysctl net.core.somaxconn=32768
_sysctl net.core.rmem_max=16777216
_sysctl net.core.wmem_max=16777216
_sysctl net.ipv4.tcp_rmem="4096 87380 16777216"
_sysctl net.ipv4.tcp_wmem="4096 87380 16777216"
_sysctl net.ipv4.tcp_tw_reuse=1
_sysctl net.ipv4.tcp_fin_timeout=15
_sysctl net.ipv4.tcp_keepalive_time=300
_sysctl net.ipv4.tcp_keepalive_intvl=30
_sysctl net.ipv4.tcp_keepalive_probes=5

# ── 1. Detect outbound network interface ──────────────────────────────────────
IFACE=$(ip route | awk '/default/ {print $5; exit}')
if [ -z "$IFACE" ]; then
    log "ERROR: Could not detect network interface" >&2
    exit 1
fi
log "INFO: Outbound interface: $IFACE"

# ── 2. Custom DNS override ────────────────────────────────────────────────────
if [ -n "${DNS_SERVER:-}" ]; then
    log "INFO: Overriding DNS with $DNS_SERVER"
    printf 'nameserver %s\n' "$DNS_SERVER" > /etc/resolv.conf
fi

# ── 3. User provisioning ──────────────────────────────────────────────────────
AUTH_ENABLED=false
PASSWD_DATA=""

provision_user() {
    local user="$1" pass="$2"
    [ -z "$user" ] && return
    [ -z "$pass" ] && return
    # Check if user exists to avoid redundant useradd calls
    if ! id "$user" >/dev/null 2>&1; then
        useradd -M -s /usr/sbin/nologin "$user"
    fi
    # Batch credentials for a single chpasswd call later (performance)
    PASSWD_DATA="${PASSWD_DATA}${user}:${pass}
"
    log "INFO: Provisioned user: $user"
}

if [ -f "/etc/proxy-users.txt" ]; then
    log "INFO: Auth mode: multi-user (file)"
    AUTH_ENABLED=true
    while IFS= read -r line; do
        case "$line" in '#'*|'') continue ;; esac

        # Split by first colon using shell parameter expansion (no forks)
        _u_raw="${line%%:*}"
        _p="${line#*:}"

        # Trim whitespace from username (only 1 fork)
        _u=$(printf '%s' "$_u_raw" | tr -d '[:space:]')
        [ -z "$_u" ] && continue

        provision_user "$_u" "$_p"
    done < /etc/proxy-users.txt
elif [ -n "${PROXY_USERS:-}" ]; then
    log "INFO: Auth mode: multi-user (env)"
    AUTH_ENABLED=true
    # Process PROXY_USERS without pipes to avoid subshells
    _save_ifs="$IFS"; IFS=','
    for pair in $PROXY_USERS; do
        IFS="$_save_ifs"
        _u="${pair%%:*}"
        _p="${pair#*:}"
        provision_user "$_u" "$_p"
        IFS=','
    done
    IFS="$_save_ifs"
elif [ -n "${PROXY_USER:-}" ] && [ -n "${PROXY_PASS:-}" ]; then
    log "INFO: Auth mode: single user ($PROXY_USER)"
    AUTH_ENABLED=true
    provision_user "$PROXY_USER" "$PROXY_PASS"
else
    log "INFO: Auth mode: none (open proxy)"
fi

# Apply all provisioned passwords in a single batch (significant performance boost for many users)
if [ -n "$PASSWD_DATA" ]; then
    printf '%s' "$PASSWD_DATA" | chpasswd
fi

# ── 4. Build Dante configuration ──────────────────────────────────────────────
SOCKSMETHOD="none"
[ "$AUTH_ENABLED" = "true" ] && SOCKSMETHOD="username"

PROTOCOL="tcp"
[ "${UDP_ENABLED:-false}" = "true" ] && PROTOCOL="tcp udp"

{
    printf '# Auto-generated by entrypoint.sh — do not edit manually\n'
    if [ "${LOG_LEVEL:-normal}" = "quiet" ]; then
        printf 'logoutput: /dev/null\n\n'
    else
        printf 'logoutput: stderr\n\n'
    fi

    printf 'internal: 0.0.0.0 port = 1080\n'
    [ "${IPV6_ENABLED:-false}" = "true" ] && printf 'internal: :: port = 1080\n'

    # Performance tuning
    printf 'internal.backlog: 512\n'
    printf 'child.maxrequests: 0\n'
    printf 'child.minspare: 5\n'
    printf 'child.maxspare: 15\n'
    printf 'socket.recvbuf.udp: 212992\n'
    printf 'socket.sendbuf.udp: 212992\n'
    printf 'socket.recvbuf.tcp: 87380\n'
    printf 'socket.sendbuf.tcp: 87380\n'
    printf 'libwrap: no\n'

    printf 'external: %s\n\n' "$IFACE"
    printf 'clientmethod: none\n'
    printf 'socksmethod: %s\n\n' "$SOCKSMETHOD"
    printf 'user.privileged: root\n'
    printf 'user.notprivileged: nobody\n\n'
    printf 'timeout.connect: %s\n'   "${TIMEOUT_CONNECT:-30}"
    printf 'timeout.negotiate: %s\n' "${TIMEOUT_NEGOTIATE:-30}"
    printf 'timeout.io: %s\n\n'      "${TIMEOUT_IO:-86400}"

    _log_rule='connect disconnect error'
    [ "${LOG_LEVEL:-normal}" = "quiet" ] && _log_rule='error'

    # Client access rules — IP allowlist
    if [ -n "${ALLOWED_CIDR:-}" ]; then
        log "INFO: Applying IP allowlist: $ALLOWED_CIDR"
        _save="$IFS"; IFS=','
        for _cidr in $ALLOWED_CIDR; do
            IFS="$_save"
            _cidr=$(printf '%s' "$_cidr" | tr -d ' ')
            printf 'client pass {\n    from: %s to: 0.0.0.0/0\n    log: %s\n}\n\n' "$_cidr" "$_log_rule"
            IFS=','
        done
        IFS="$_save"
        printf 'client block {\n    from: 0.0.0.0/0 to: 0.0.0.0/0\n    log: error\n}\n\n'
    else
        printf 'client pass {\n    from: 0.0.0.0/0 to: 0.0.0.0/0\n    log: %s\n}\n\n' "$_log_rule"
    fi

    # Destination block rules
    if [ -n "${BLOCKED_DESTINATIONS:-}" ]; then
        log "INFO: Blocking destinations: $BLOCKED_DESTINATIONS"
        _save="$IFS"; IFS=','
        for _dest in $BLOCKED_DESTINATIONS; do
            IFS="$_save"
            _dest=$(printf '%s' "$_dest" | tr -d ' ')
            printf 'socks block {\n    from: 0.0.0.0/0 to: %s\n    log: error\n}\n\n' "$_dest"
            IFS=','
        done
        IFS="$_save"
    fi

    # Main socks pass rule
    printf 'socks pass {\n'
    printf '    from: 0.0.0.0/0 to: 0.0.0.0/0\n'
    printf '    protocol: %s\n' "$PROTOCOL"
    printf '    log: %s\n' "$_log_rule"
    printf '}\n'

    # Tor outbound route
    if [ "${TOR_ENABLED:-false}" = "true" ]; then
        printf '\nroute {\n'
        printf '    from: 0.0.0.0/0 to: 0.0.0.0/0 via: 127.0.0.1 port = 9050\n'
        printf '    protocol: tcp\n'
        printf '    method: none\n'
        printf '    proxyprotocol: socks_v5\n'
        printf '}\n'
    fi
} > "$CONF"

log "INFO: Dante configuration written to $CONF"

# ── 5. Start Tor (if enabled) ─────────────────────────────────────────────────
if [ "${TOR_ENABLED:-false}" = "true" ]; then
    log "INFO: Starting Tor daemon..."
    mkdir -p /tmp/tor-data
    chmod 700 /tmp/tor-data
    tor --RunAsDaemon 1 \
        --SocksPort 9050 \
        --DataDirectory /tmp/tor-data \
        --Log "notice file /tmp/tor-data/notices.log"

    log "INFO: Waiting for Tor to be ready..."
    _i=0
    while [ "$_i" -lt 30 ]; do
        nc -w 1 127.0.0.1 9050 </dev/null 2>/dev/null && break
        sleep 1
        _i=$((_i + 1))
    done

    if nc -w 1 127.0.0.1 9050 </dev/null 2>/dev/null; then
        log "INFO: Tor ready on 127.0.0.1:9050"
    else
        log "WARN: Tor did not become ready in time — continuing anyway"
    fi
fi

# ── 6. Start Dante ────────────────────────────────────────────────────────────
sockd -f "$CONF" &
SOCKD_PID=$!
log "INFO: Dante started (PID $SOCKD_PID)"


# Forward SIGHUP to sockd for live config reload
trap 'log "INFO: Reloading Dante config..."; kill -HUP "$SOCKD_PID" 2>/dev/null' HUP

# Graceful shutdown on SIGTERM / SIGINT
trap 'log "INFO: Shutting down..."; kill -TERM "$SOCKD_PID" 2>/dev/null; wait "$SOCKD_PID" 2>/dev/null; exit 0' TERM INT

wait "$SOCKD_PID"
