#!/bin/sh
set -e

CONF=/etc/danted.conf

log() { printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >&2; }

# ── 1. Detect outbound network interface ──────────────────────────────────────
IFACE=$(ip route | awk '/default/ {print $5; exit}')
if [ -z "$IFACE" ]; then
    log "ERROR: Could not detect network interface" >&2
    exit 1
fi
log "INFO: Outbound interface: $IFACE"

# ── 2. Custom DNS override ────────────────────────────────────────────────────
if [ -n "${DNS_SERVER:-}" ]; then
    log "INFO: Overriding DNS with $DNS_SERVER"
    printf 'nameserver %s\n' "$DNS_SERVER" > /etc/resolv.conf
fi

# ── 3. User provisioning ──────────────────────────────────────────────────────
AUTH_ENABLED=false

provision_user() {
    local user="$1" pass="$2"
    [ -z "$user" ] && return
    [ -z "$pass" ] && return
    if ! id "$user" >/dev/null 2>&1; then
        useradd -M -s /usr/sbin/nologin "$user"
    fi
    printf '%s:%s\n' "$user" "$pass" | chpasswd
    log "INFO: Provisioned user: $user"
}

if [ -f "/etc/proxy-users.txt" ]; then
    log "INFO: Auth mode: multi-user (file)"
    AUTH_ENABLED=true
    while IFS= read -r line; do
        case "$line" in '#'*|'') continue ;; esac
        [ -z "$(printf '%s' "$line" | tr -d ' \t')" ] && continue
        _u=$(printf '%s' "$line" | cut -d: -f1 | tr -d ' \t')
        _p=$(printf '%s' "$line" | cut -d: -f2-)
        provision_user "$_u" "$_p"
    done < /etc/proxy-users.txt
elif [ -n "${PROXY_USERS:-}" ]; then
    log "INFO: Auth mode: multi-user (env)"
    AUTH_ENABLED=true
    printf '%s' "$PROXY_USERS" | tr ',' '\n' | while IFS= read -r pair; do
        _u=$(printf '%s' "$pair" | cut -d: -f1)
        _p=$(printf '%s' "$pair" | cut -d: -f2-)
        provision_user "$_u" "$_p"
    done
elif [ -n "${PROXY_USER:-}" ] && [ -n "${PROXY_PASS:-}" ]; then
    log "INFO: Auth mode: single user ($PROXY_USER)"
    AUTH_ENABLED=true
    provision_user "$PROXY_USER" "$PROXY_PASS"
else
    log "INFO: Auth mode: none (open proxy)"
fi

# ── 4. Build Dante configuration ──────────────────────────────────────────────
SOCKSMETHOD="none"
[ "$AUTH_ENABLED" = "true" ] && SOCKSMETHOD="username"

PROTOCOL="tcp"
[ "${UDP_ENABLED:-false}" = "true" ] && PROTOCOL="tcp udp"

{
    printf '# Auto-generated by entrypoint.sh — do not edit manually\n'
    printf 'logoutput: stderr\n\n'

    printf 'internal: 0.0.0.0 port = 1080\n'
    [ "${IPV6_ENABLED:-false}" = "true" ] && printf 'internal: :: port = 1080\n'

    printf 'external: %s\n\n' "$IFACE"
    printf 'clientmethod: none\n'
    printf 'socksmethod: %s\n\n' "$SOCKSMETHOD"
    printf 'user.privileged: root\n'
    printf 'user.notprivileged: nobody\n\n'
    printf 'timeout.connect: %s\n'   "${TIMEOUT_CONNECT:-30}"
    printf 'timeout.negotiate: %s\n' "${TIMEOUT_NEGOTIATE:-30}"
    printf 'timeout.io: %s\n\n'      "${TIMEOUT_IO:-86400}"

    # Client access rules — IP allowlist
    if [ -n "${ALLOWED_CIDR:-}" ]; then
        log "INFO: Applying IP allowlist: $ALLOWED_CIDR"
        _save="$IFS"; IFS=','
        for _cidr in $ALLOWED_CIDR; do
            IFS="$_save"
            _cidr=$(printf '%s' "$_cidr" | tr -d ' ')
            printf 'client pass {\n    from: %s to: 0.0.0.0/0\n    log: connect disconnect error\n}\n\n' "$_cidr"
            IFS=','
        done
        IFS="$_save"
        printf 'client block {\n    from: 0.0.0.0/0 to: 0.0.0.0/0\n    log: connect error\n}\n\n'
    else
        printf 'client pass {\n    from: 0.0.0.0/0 to: 0.0.0.0/0\n    log: connect disconnect error\n}\n\n'
    fi

    # Destination block rules
    if [ -n "${BLOCKED_DESTINATIONS:-}" ]; then
        log "INFO: Blocking destinations: $BLOCKED_DESTINATIONS"
        _save="$IFS"; IFS=','
        for _dest in $BLOCKED_DESTINATIONS; do
            IFS="$_save"
            _dest=$(printf '%s' "$_dest" | tr -d ' ')
            printf 'socks block {\n    from: 0.0.0.0/0 to: %s\n    log: connect error\n}\n\n' "$_dest"
            IFS=','
        done
        IFS="$_save"
    fi

    # Main socks pass rule
    printf 'socks pass {\n'
    printf '    from: 0.0.0.0/0 to: 0.0.0.0/0\n'
    printf '    protocol: %s\n' "$PROTOCOL"
    printf '    log: connect disconnect error\n'
    printf '}\n'

    # Tor outbound route
    if [ "${TOR_ENABLED:-false}" = "true" ]; then
        printf '\nroute {\n'
        printf '    from: 0.0.0.0/0 to: 0.0.0.0/0 via: 127.0.0.1 port = 9050\n'
        printf '    protocol: tcp\n'
        printf '    method: none\n'
        printf '    proxyprotocol: socks_v5\n'
        printf '}\n'
    fi
} > "$CONF"

log "INFO: Dante configuration written to $CONF"

# ── 5. Start Tor (if enabled) ─────────────────────────────────────────────────
if [ "${TOR_ENABLED:-false}" = "true" ]; then
    log "INFO: Starting Tor daemon..."
    mkdir -p /tmp/tor-data
    chmod 700 /tmp/tor-data
    tor --RunAsDaemon 1 \
        --SocksPort 9050 \
        --DataDirectory /tmp/tor-data \
        --Log "notice file /tmp/tor-data/notices.log"

    log "INFO: Waiting for Tor to be ready..."
    _i=0
    while [ "$_i" -lt 30 ]; do
        nc -w 1 127.0.0.1 9050 </dev/null 2>/dev/null && break
        sleep 1
        _i=$((_i + 1))
    done

    if nc -w 1 127.0.0.1 9050 </dev/null 2>/dev/null; then
        log "INFO: Tor ready on 127.0.0.1:9050"
    else
        log "WARN: Tor did not become ready in time — continuing anyway"
    fi
fi

# ── 6. Start stunnel TLS wrapper (if enabled) ─────────────────────────────────
if [ "${TLS_ENABLED:-false}" = "true" ]; then
    TLS_CERT="${TLS_CERT:-/etc/stunnel/stunnel.pem}"
    TLS_PORT="${TLS_PORT:-1443}"
    mkdir -p /etc/stunnel

    if [ ! -f "$TLS_CERT" ]; then
        log "INFO: Generating self-signed TLS certificate..."
        openssl req -new -x509 -days 3650 -nodes \
            -subj "/CN=socks5-proxy" \
            -out /etc/stunnel/stunnel.pem \
            -keyout /etc/stunnel/stunnel.pem 2>/dev/null
        chmod 600 /etc/stunnel/stunnel.pem
        TLS_CERT=/etc/stunnel/stunnel.pem
        log "INFO: Self-signed certificate generated at $TLS_CERT"
    fi

    cat > /etc/stunnel/stunnel.conf <<STUNCONF
foreground = no
pid = /var/run/stunnel.pid

[socks5-tls]
accept  = $TLS_PORT
connect = 127.0.0.1:1080
cert    = $TLS_CERT
STUNCONF

    stunnel /etc/stunnel/stunnel.conf
    log "INFO: stunnel TLS wrapper started on port $TLS_PORT"
fi

# ── 7. Start Dante ────────────────────────────────────────────────────────────
sockd -f "$CONF" &
SOCKD_PID=$!
log "INFO: Dante started (PID $SOCKD_PID)"

# Forward SIGHUP to sockd for live config reload
trap 'log "INFO: Reloading Dante config..."; kill -HUP "$SOCKD_PID" 2>/dev/null' HUP

# Graceful shutdown on SIGTERM / SIGINT
trap 'log "INFO: Shutting down..."; kill -TERM "$SOCKD_PID" 2>/dev/null; wait "$SOCKD_PID" 2>/dev/null; exit 0' TERM INT

wait "$SOCKD_PID"
